// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.6.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decode32`, `ratchet_message_key`

/// 生成新的主密钥对，返回 (user_id, 主私钥 hex, 主公钥 hex)。
/// 主私钥仅应由 Dart 侧存入系统安全存储，Rust 层不持久化。
IdentityBundle generateIdentity() =>
    RustLib.instance.api.crateApiGenerateIdentity();

/// 从主私钥 hex 恢复主密钥对，返回 (user_id, 主公钥 hex)。
IdentityBundle restoreIdentity({required String masterSecretHex}) => RustLib
    .instance
    .api
    .crateApiRestoreIdentity(masterSecretHex: masterSecretHex);

/// 生成设备密钥对，返回 (device_id, 设备私钥 hex, 设备公钥 hex)。
DeviceBundle generateDevice() => RustLib.instance.api.crateApiGenerateDevice();

/// 用主私钥为设备签发证书（首设备自签）。
/// 返回设备证书的 protobuf 编码 hex。
String issueDeviceCertificate({
  required String masterSecretHex,
  required String userId,
  required String devicePubkeyHex,
  required String deviceName,
}) => RustLib.instance.api.crateApiIssueDeviceCertificate(
  masterSecretHex: masterSecretHex,
  userId: userId,
  devicePubkeyHex: devicePubkeyHex,
  deviceName: deviceName,
);

/// 构造发送消息的签名载荷签名。
/// 输入：设备私钥 hex、topic_id、msg_id、author_id、device_id、client_ts、text、reply_to。
/// 返回消息签名 hex。
String signSendMessage({
  required String deviceSecretHex,
  required String topicId,
  required String msgId,
  required String authorId,
  required String deviceId,
  required PlatformInt64 clientTs,
  required String text,
  required String replyTo,
}) => RustLib.instance.api.crateApiSignSendMessage(
  deviceSecretHex: deviceSecretHex,
  topicId: topicId,
  msgId: msgId,
  authorId: authorId,
  deviceId: deviceId,
  clientTs: clientTs,
  text: text,
  replyTo: replyTo,
);

/// 通用设备签名：对任意 payload 字节用设备私钥签名。
/// 输入：设备私钥 hex、payload hex。返回签名 hex。
String signPayload({
  required String deviceSecretHex,
  required String payloadHex,
}) => RustLib.instance.api.crateApiSignPayload(
  deviceSecretHex: deviceSecretHex,
  payloadHex: payloadHex,
);

/// 构造带附件消息的签名（F-MEDIA-1：附件元数据纳入载荷）。
/// 载荷与 core signature::send_message_signing_payload 的附件段一致。
String signSendMessageWithAttachment({
  required String deviceSecretHex,
  required String topicId,
  required String msgId,
  required String authorId,
  required String deviceId,
  required PlatformInt64 clientTs,
  required String text,
  required String attachmentId,
  required String kind,
  required PlatformInt64 size,
  required String mime,
  required PlatformInt64 width,
  required PlatformInt64 height,
  required PlatformInt64 duration,
  required String thumbnailId,
  required String filename,
}) => RustLib.instance.api.crateApiSignSendMessageWithAttachment(
  deviceSecretHex: deviceSecretHex,
  topicId: topicId,
  msgId: msgId,
  authorId: authorId,
  deviceId: deviceId,
  clientTs: clientTs,
  text: text,
  attachmentId: attachmentId,
  kind: kind,
  size: size,
  mime: mime,
  width: width,
  height: height,
  duration: duration,
  thumbnailId: thumbnailId,
  filename: filename,
);

/// 验证服务器迁移公告签名（F-JOIN-8）。
/// 载荷与 server 端 admin::migration_signing_payload 一致：
/// "lonisle-migrate-v1\0{address}\0{fingerprint}\0{server_id}"
bool verifyMigrationSignature({
  required String serverPubkeyHex,
  required String address,
  required String fingerprint,
  required String serverId,
  required String signatureHex,
}) => RustLib.instance.api.crateApiVerifyMigrationSignature(
  serverPubkeyHex: serverPubkeyHex,
  address: address,
  fingerprint: fingerprint,
  serverId: serverId,
  signatureHex: signatureHex,
);

/// 构造 Hello 握手签名（在 Rust 侧统一构造载荷，与 server 端一致）。
/// 输入：设备私钥 hex、协议版本、user_id、master_pubkey_hex、display_name、设备证书 hex。
/// 返回签名 hex。
String signHello({
  required String deviceSecretHex,
  required int protocolVersion,
  required String userId,
  required String masterPubkeyHex,
  required String displayName,
  required String deviceCertHex,
}) => RustLib.instance.api.crateApiSignHello(
  deviceSecretHex: deviceSecretHex,
  protocolVersion: protocolVersion,
  userId: userId,
  masterPubkeyHex: masterPubkeyHex,
  displayName: displayName,
  deviceCertHex: deviceCertHex,
);

/// 签发吊销证明（主私钥对「被吊销设备公钥」签名）。
/// 返回吊销证明的 protobuf 编码 hex。
String issueRevocation({
  required String masterSecretHex,
  required String userId,
  required String devicePubkeyHex,
}) => RustLib.instance.api.crateApiIssueRevocation(
  masterSecretHex: masterSecretHex,
  userId: userId,
  devicePubkeyHex: devicePubkeyHex,
);

/// 生成主密钥助记词（24 词）。仅可在已认证设备上、经用户确认后调用。
String generateMnemonic({required String masterSecretHex}) => RustLib
    .instance
    .api
    .crateApiGenerateMnemonic(masterSecretHex: masterSecretHex);

/// 从助记词恢复主私钥（返回主私钥 hex）。
String recoverFromMnemonic({required String mnemonic}) =>
    RustLib.instance.api.crateApiRecoverFromMnemonic(mnemonic: mnemonic);

/// 校验助记词是否合法。
bool validateMnemonic({required String mnemonic}) =>
    RustLib.instance.api.crateApiValidateMnemonic(mnemonic: mnemonic);

/// 派生本地数据库加密密钥（SQLCipher），密钥派生自设备私钥。
/// 返回 32 字节 hex。密钥在 Rust 侧派生，避免明文出现在 Dart 侧。
String deriveDbKey({required String deviceSecretHex}) =>
    RustLib.instance.api.crateApiDeriveDbKey(deviceSecretHex: deviceSecretHex);

/// 生成 X25519 密钥对。
X25519Bundle generateX25519() => RustLib.instance.api.crateApiGenerateX25519();

/// X3DH 协商（发起方），返回根密钥 hex。
String x3DhInitiate({
  required String ikSecretHex,
  required String ekSecretHex,
  required String peerIkHex,
  required String peerSpkHex,
  String? peerOpkHex,
}) => RustLib.instance.api.crateApiX3DhInitiate(
  ikSecretHex: ikSecretHex,
  ekSecretHex: ekSecretHex,
  peerIkHex: peerIkHex,
  peerSpkHex: peerSpkHex,
  peerOpkHex: peerOpkHex,
);

/// 验证对端预密钥束的 SPK 签名（主身份 Ed25519 公钥对 SPK 签名，F-DEV）。
bool verifySpkSignature({
  required String masterPubkeyHex,
  required String spkPubHex,
  required String signatureHex,
}) => RustLib.instance.api.crateApiVerifySpkSignature(
  masterPubkeyHex: masterPubkeyHex,
  spkPubHex: spkPubHex,
  signatureHex: signatureHex,
);

/// 建立会话（发起方）：X3DH 协商 + 初始化双棘轮。
/// 返回可持久化的会话状态 hex（后续 encrypt/decrypt 传入）。
E2eeSessionOutput e2EeEstablishInitiator({
  required String ikSecretHex,
  required String ekSecretHex,
  required String peerIkHex,
  required String peerSpkHex,
  String? peerOpkHex,
}) => RustLib.instance.api.crateApiE2EeEstablishInitiator(
  ikSecretHex: ikSecretHex,
  ekSecretHex: ekSecretHex,
  peerIkHex: peerIkHex,
  peerSpkHex: peerSpkHex,
  peerOpkHex: peerOpkHex,
);

/// 建立会话（响应方）：X3DH 协商 + 初始化双棘轮。
E2eeSessionOutput e2EeEstablishResponder({
  required String ikSecretHex,
  required String spkSecretHex,
  String? opkSecretHex,
  required String peerIkHex,
  required String peerEkHex,
}) => RustLib.instance.api.crateApiE2EeEstablishResponder(
  ikSecretHex: ikSecretHex,
  spkSecretHex: spkSecretHex,
  opkSecretHex: opkSecretHex,
  peerIkHex: peerIkHex,
  peerEkHex: peerEkHex,
);

/// E2EE 会话加密（双棘轮）。返回新状态 + 密文（含 header）。
E2eeSessionOutput e2EeSessionEncrypt({
  required String stateHex,
  required String plaintextHex,
}) => RustLib.instance.api.crateApiE2EeSessionEncrypt(
  stateHex: stateHex,
  plaintextHex: plaintextHex,
);

/// E2EE 会话解密（双棘轮，支持乱序）。返回新状态 + 明文。
E2eeSessionOutput e2EeSessionDecrypt({
  required String stateHex,
  required String ciphertextHex,
}) => RustLib.instance.api.crateApiE2EeSessionDecrypt(
  stateHex: stateHex,
  ciphertextHex: ciphertextHex,
);

/// 兼容旧接口：E2EE 加密（无状态对称棘轮）。
/// 仅供测试/过渡使用，正式链路用 e2ee_session_encrypt。
String e2EeEncrypt({
  required String rootHex,
  required int msgNumber,
  required String plaintextHex,
}) => RustLib.instance.api.crateApiE2EeEncrypt(
  rootHex: rootHex,
  msgNumber: msgNumber,
  plaintextHex: plaintextHex,
);

/// 兼容旧接口：E2EE 解密。
String e2EeDecrypt({
  required String rootHex,
  required int msgNumber,
  required String ciphertextHex,
}) => RustLib.instance.api.crateApiE2EeDecrypt(
  rootHex: rootHex,
  msgNumber: msgNumber,
  ciphertextHex: ciphertextHex,
);

/// 设备信息包
class DeviceBundle {
  final String deviceId;
  final String deviceSecretHex;
  final String devicePubkeyHex;

  const DeviceBundle({
    required this.deviceId,
    required this.deviceSecretHex,
    required this.devicePubkeyHex,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^ deviceSecretHex.hashCode ^ devicePubkeyHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceBundle &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          deviceSecretHex == other.deviceSecretHex &&
          devicePubkeyHex == other.devicePubkeyHex;
}

/// E2EE 会话操作结果：新状态 hex + 载荷 hex
class E2eeSessionOutput {
  final String newStateHex;
  final String payloadHex;

  const E2eeSessionOutput({
    required this.newStateHex,
    required this.payloadHex,
  });

  @override
  int get hashCode => newStateHex.hashCode ^ payloadHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is E2eeSessionOutput &&
          runtimeType == other.runtimeType &&
          newStateHex == other.newStateHex &&
          payloadHex == other.payloadHex;
}

/// 身份信息包
class IdentityBundle {
  final String userId;
  final String displayName;
  final String masterSecretHex;
  final String masterPubkeyHex;
  final String avatarSeed;

  const IdentityBundle({
    required this.userId,
    required this.displayName,
    required this.masterSecretHex,
    required this.masterPubkeyHex,
    required this.avatarSeed,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      displayName.hashCode ^
      masterSecretHex.hashCode ^
      masterPubkeyHex.hashCode ^
      avatarSeed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentityBundle &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          displayName == other.displayName &&
          masterSecretHex == other.masterSecretHex &&
          masterPubkeyHex == other.masterPubkeyHex &&
          avatarSeed == other.avatarSeed;
}

/// X25519 密钥对
class X25519Bundle {
  final String secretHex;
  final String publicHex;

  const X25519Bundle({required this.secretHex, required this.publicHex});

  @override
  int get hashCode => secretHex.hashCode ^ publicHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is X25519Bundle &&
          runtimeType == other.runtimeType &&
          secretHex == other.secretHex &&
          publicHex == other.publicHex;
}
