// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.6.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0-beta.6';

  @override
  int get rustContentHash => 1420310806;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'lonisle_client_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  String crateApiDeriveDbKey({required String deviceSecretHex});

  String crateApiE2EeDecrypt({
    required String rootHex,
    required int msgNumber,
    required String ciphertextHex,
  });

  String crateApiE2EeEncrypt({
    required String rootHex,
    required int msgNumber,
    required String plaintextHex,
  });

  E2eeSessionOutput crateApiE2EeEstablishInitiator({
    required String ikSecretHex,
    required String ekSecretHex,
    required String peerIkHex,
    required String peerSpkHex,
    String? peerOpkHex,
  });

  E2eeSessionOutput crateApiE2EeEstablishResponder({
    required String ikSecretHex,
    required String spkSecretHex,
    String? opkSecretHex,
    required String peerIkHex,
    required String peerEkHex,
  });

  E2eeSessionOutput crateApiE2EeSessionDecrypt({
    required String stateHex,
    required String ciphertextHex,
  });

  E2eeSessionOutput crateApiE2EeSessionEncrypt({
    required String stateHex,
    required String plaintextHex,
  });

  DeviceBundle crateApiGenerateDevice();

  IdentityBundle crateApiGenerateIdentity();

  String crateApiGenerateMnemonic({required String masterSecretHex});

  X25519Bundle crateApiGenerateX25519();

  String crateApiIssueDeviceCertificate({
    required String masterSecretHex,
    required String userId,
    required String devicePubkeyHex,
    required String deviceName,
  });

  String crateApiIssueRevocation({
    required String masterSecretHex,
    required String userId,
    required String devicePubkeyHex,
  });

  String crateApiRecoverFromMnemonic({required String mnemonic});

  IdentityBundle crateApiRestoreIdentity({required String masterSecretHex});

  String crateApiSignHello({
    required String deviceSecretHex,
    required int protocolVersion,
    required String userId,
    required String masterPubkeyHex,
    required String displayName,
    required String deviceCertHex,
  });

  String crateApiSignPayload({
    required String deviceSecretHex,
    required String payloadHex,
  });

  String crateApiSignSendMessage({
    required String deviceSecretHex,
    required String topicId,
    required String msgId,
    required String authorId,
    required String deviceId,
    required PlatformInt64 clientTs,
    required String text,
    required String replyTo,
  });

  String crateApiSignSendMessageWithAttachment({
    required String deviceSecretHex,
    required String topicId,
    required String msgId,
    required String authorId,
    required String deviceId,
    required PlatformInt64 clientTs,
    required String text,
    required String attachmentId,
    required String kind,
    required PlatformInt64 size,
    required String mime,
    required PlatformInt64 width,
    required PlatformInt64 height,
    required PlatformInt64 duration,
    required String thumbnailId,
    required String filename,
  });

  bool crateApiValidateMnemonic({required String mnemonic});

  bool crateApiVerifyMigrationSignature({
    required String serverPubkeyHex,
    required String address,
    required String fingerprint,
    required String serverId,
    required String signatureHex,
  });

  bool crateApiVerifySpkSignature({
    required String masterPubkeyHex,
    required String spkPubHex,
    required String signatureHex,
  });

  String crateApiX3DhInitiate({
    required String ikSecretHex,
    required String ekSecretHex,
    required String peerIkHex,
    required String peerSpkHex,
    String? peerOpkHex,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiDeriveDbKey({required String deviceSecretHex}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(deviceSecretHex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDeriveDbKeyConstMeta,
        argValues: [deviceSecretHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeriveDbKeyConstMeta => const TaskConstMeta(
    debugName: "derive_db_key",
    argNames: ["deviceSecretHex"],
  );

  @override
  String crateApiE2EeDecrypt({
    required String rootHex,
    required int msgNumber,
    required String ciphertextHex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(rootHex, serializer);
          sse_encode_u_32(msgNumber, serializer);
          sse_encode_String(ciphertextHex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiE2EeDecryptConstMeta,
        argValues: [rootHex, msgNumber, ciphertextHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiE2EeDecryptConstMeta => const TaskConstMeta(
    debugName: "e2ee_decrypt",
    argNames: ["rootHex", "msgNumber", "ciphertextHex"],
  );

  @override
  String crateApiE2EeEncrypt({
    required String rootHex,
    required int msgNumber,
    required String plaintextHex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(rootHex, serializer);
          sse_encode_u_32(msgNumber, serializer);
          sse_encode_String(plaintextHex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiE2EeEncryptConstMeta,
        argValues: [rootHex, msgNumber, plaintextHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiE2EeEncryptConstMeta => const TaskConstMeta(
    debugName: "e2ee_encrypt",
    argNames: ["rootHex", "msgNumber", "plaintextHex"],
  );

  @override
  E2eeSessionOutput crateApiE2EeEstablishInitiator({
    required String ikSecretHex,
    required String ekSecretHex,
    required String peerIkHex,
    required String peerSpkHex,
    String? peerOpkHex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ikSecretHex, serializer);
          sse_encode_String(ekSecretHex, serializer);
          sse_encode_String(peerIkHex, serializer);
          sse_encode_String(peerSpkHex, serializer);
          sse_encode_opt_String(peerOpkHex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_e_2_ee_session_output,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiE2EeEstablishInitiatorConstMeta,
        argValues: [
          ikSecretHex,
          ekSecretHex,
          peerIkHex,
          peerSpkHex,
          peerOpkHex,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiE2EeEstablishInitiatorConstMeta =>
      const TaskConstMeta(
        debugName: "e2ee_establish_initiator",
        argNames: [
          "ikSecretHex",
          "ekSecretHex",
          "peerIkHex",
          "peerSpkHex",
          "peerOpkHex",
        ],
      );

  @override
  E2eeSessionOutput crateApiE2EeEstablishResponder({
    required String ikSecretHex,
    required String spkSecretHex,
    String? opkSecretHex,
    required String peerIkHex,
    required String peerEkHex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ikSecretHex, serializer);
          sse_encode_String(spkSecretHex, serializer);
          sse_encode_opt_String(opkSecretHex, serializer);
          sse_encode_String(peerIkHex, serializer);
          sse_encode_String(peerEkHex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_e_2_ee_session_output,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiE2EeEstablishResponderConstMeta,
        argValues: [
          ikSecretHex,
          spkSecretHex,
          opkSecretHex,
          peerIkHex,
          peerEkHex,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiE2EeEstablishResponderConstMeta =>
      const TaskConstMeta(
        debugName: "e2ee_establish_responder",
        argNames: [
          "ikSecretHex",
          "spkSecretHex",
          "opkSecretHex",
          "peerIkHex",
          "peerEkHex",
        ],
      );

  @override
  E2eeSessionOutput crateApiE2EeSessionDecrypt({
    required String stateHex,
    required String ciphertextHex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(stateHex, serializer);
          sse_encode_String(ciphertextHex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_e_2_ee_session_output,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiE2EeSessionDecryptConstMeta,
        argValues: [stateHex, ciphertextHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiE2EeSessionDecryptConstMeta => const TaskConstMeta(
    debugName: "e2ee_session_decrypt",
    argNames: ["stateHex", "ciphertextHex"],
  );

  @override
  E2eeSessionOutput crateApiE2EeSessionEncrypt({
    required String stateHex,
    required String plaintextHex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(stateHex, serializer);
          sse_encode_String(plaintextHex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_e_2_ee_session_output,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiE2EeSessionEncryptConstMeta,
        argValues: [stateHex, plaintextHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiE2EeSessionEncryptConstMeta => const TaskConstMeta(
    debugName: "e2ee_session_encrypt",
    argNames: ["stateHex", "plaintextHex"],
  );

  @override
  DeviceBundle crateApiGenerateDevice() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_device_bundle,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGenerateDeviceConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenerateDeviceConstMeta =>
      const TaskConstMeta(debugName: "generate_device", argNames: []);

  @override
  IdentityBundle crateApiGenerateIdentity() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_identity_bundle,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGenerateIdentityConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenerateIdentityConstMeta =>
      const TaskConstMeta(debugName: "generate_identity", argNames: []);

  @override
  String crateApiGenerateMnemonic({required String masterSecretHex}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(masterSecretHex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGenerateMnemonicConstMeta,
        argValues: [masterSecretHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenerateMnemonicConstMeta => const TaskConstMeta(
    debugName: "generate_mnemonic",
    argNames: ["masterSecretHex"],
  );

  @override
  X25519Bundle crateApiGenerateX25519() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_x_25519_bundle,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGenerateX25519ConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenerateX25519ConstMeta =>
      const TaskConstMeta(debugName: "generate_x25519", argNames: []);

  @override
  String crateApiIssueDeviceCertificate({
    required String masterSecretHex,
    required String userId,
    required String devicePubkeyHex,
    required String deviceName,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(masterSecretHex, serializer);
          sse_encode_String(userId, serializer);
          sse_encode_String(devicePubkeyHex, serializer);
          sse_encode_String(deviceName, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIssueDeviceCertificateConstMeta,
        argValues: [masterSecretHex, userId, devicePubkeyHex, deviceName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIssueDeviceCertificateConstMeta =>
      const TaskConstMeta(
        debugName: "issue_device_certificate",
        argNames: [
          "masterSecretHex",
          "userId",
          "devicePubkeyHex",
          "deviceName",
        ],
      );

  @override
  String crateApiIssueRevocation({
    required String masterSecretHex,
    required String userId,
    required String devicePubkeyHex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(masterSecretHex, serializer);
          sse_encode_String(userId, serializer);
          sse_encode_String(devicePubkeyHex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIssueRevocationConstMeta,
        argValues: [masterSecretHex, userId, devicePubkeyHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIssueRevocationConstMeta => const TaskConstMeta(
    debugName: "issue_revocation",
    argNames: ["masterSecretHex", "userId", "devicePubkeyHex"],
  );

  @override
  String crateApiRecoverFromMnemonic({required String mnemonic}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRecoverFromMnemonicConstMeta,
        argValues: [mnemonic],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRecoverFromMnemonicConstMeta =>
      const TaskConstMeta(
        debugName: "recover_from_mnemonic",
        argNames: ["mnemonic"],
      );

  @override
  IdentityBundle crateApiRestoreIdentity({required String masterSecretHex}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(masterSecretHex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_identity_bundle,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRestoreIdentityConstMeta,
        argValues: [masterSecretHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRestoreIdentityConstMeta => const TaskConstMeta(
    debugName: "restore_identity",
    argNames: ["masterSecretHex"],
  );

  @override
  String crateApiSignHello({
    required String deviceSecretHex,
    required int protocolVersion,
    required String userId,
    required String masterPubkeyHex,
    required String displayName,
    required String deviceCertHex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(deviceSecretHex, serializer);
          sse_encode_i_32(protocolVersion, serializer);
          sse_encode_String(userId, serializer);
          sse_encode_String(masterPubkeyHex, serializer);
          sse_encode_String(displayName, serializer);
          sse_encode_String(deviceCertHex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSignHelloConstMeta,
        argValues: [
          deviceSecretHex,
          protocolVersion,
          userId,
          masterPubkeyHex,
          displayName,
          deviceCertHex,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSignHelloConstMeta => const TaskConstMeta(
    debugName: "sign_hello",
    argNames: [
      "deviceSecretHex",
      "protocolVersion",
      "userId",
      "masterPubkeyHex",
      "displayName",
      "deviceCertHex",
    ],
  );

  @override
  String crateApiSignPayload({
    required String deviceSecretHex,
    required String payloadHex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(deviceSecretHex, serializer);
          sse_encode_String(payloadHex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSignPayloadConstMeta,
        argValues: [deviceSecretHex, payloadHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSignPayloadConstMeta => const TaskConstMeta(
    debugName: "sign_payload",
    argNames: ["deviceSecretHex", "payloadHex"],
  );

  @override
  String crateApiSignSendMessage({
    required String deviceSecretHex,
    required String topicId,
    required String msgId,
    required String authorId,
    required String deviceId,
    required PlatformInt64 clientTs,
    required String text,
    required String replyTo,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(deviceSecretHex, serializer);
          sse_encode_String(topicId, serializer);
          sse_encode_String(msgId, serializer);
          sse_encode_String(authorId, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_i_64(clientTs, serializer);
          sse_encode_String(text, serializer);
          sse_encode_String(replyTo, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSignSendMessageConstMeta,
        argValues: [
          deviceSecretHex,
          topicId,
          msgId,
          authorId,
          deviceId,
          clientTs,
          text,
          replyTo,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSignSendMessageConstMeta => const TaskConstMeta(
    debugName: "sign_send_message",
    argNames: [
      "deviceSecretHex",
      "topicId",
      "msgId",
      "authorId",
      "deviceId",
      "clientTs",
      "text",
      "replyTo",
    ],
  );

  @override
  String crateApiSignSendMessageWithAttachment({
    required String deviceSecretHex,
    required String topicId,
    required String msgId,
    required String authorId,
    required String deviceId,
    required PlatformInt64 clientTs,
    required String text,
    required String attachmentId,
    required String kind,
    required PlatformInt64 size,
    required String mime,
    required PlatformInt64 width,
    required PlatformInt64 height,
    required PlatformInt64 duration,
    required String thumbnailId,
    required String filename,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(deviceSecretHex, serializer);
          sse_encode_String(topicId, serializer);
          sse_encode_String(msgId, serializer);
          sse_encode_String(authorId, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_i_64(clientTs, serializer);
          sse_encode_String(text, serializer);
          sse_encode_String(attachmentId, serializer);
          sse_encode_String(kind, serializer);
          sse_encode_i_64(size, serializer);
          sse_encode_String(mime, serializer);
          sse_encode_i_64(width, serializer);
          sse_encode_i_64(height, serializer);
          sse_encode_i_64(duration, serializer);
          sse_encode_String(thumbnailId, serializer);
          sse_encode_String(filename, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSignSendMessageWithAttachmentConstMeta,
        argValues: [
          deviceSecretHex,
          topicId,
          msgId,
          authorId,
          deviceId,
          clientTs,
          text,
          attachmentId,
          kind,
          size,
          mime,
          width,
          height,
          duration,
          thumbnailId,
          filename,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSignSendMessageWithAttachmentConstMeta =>
      const TaskConstMeta(
        debugName: "sign_send_message_with_attachment",
        argNames: [
          "deviceSecretHex",
          "topicId",
          "msgId",
          "authorId",
          "deviceId",
          "clientTs",
          "text",
          "attachmentId",
          "kind",
          "size",
          "mime",
          "width",
          "height",
          "duration",
          "thumbnailId",
          "filename",
        ],
      );

  @override
  bool crateApiValidateMnemonic({required String mnemonic}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiValidateMnemonicConstMeta,
        argValues: [mnemonic],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiValidateMnemonicConstMeta => const TaskConstMeta(
    debugName: "validate_mnemonic",
    argNames: ["mnemonic"],
  );

  @override
  bool crateApiVerifyMigrationSignature({
    required String serverPubkeyHex,
    required String address,
    required String fingerprint,
    required String serverId,
    required String signatureHex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverPubkeyHex, serializer);
          sse_encode_String(address, serializer);
          sse_encode_String(fingerprint, serializer);
          sse_encode_String(serverId, serializer);
          sse_encode_String(signatureHex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVerifyMigrationSignatureConstMeta,
        argValues: [
          serverPubkeyHex,
          address,
          fingerprint,
          serverId,
          signatureHex,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVerifyMigrationSignatureConstMeta =>
      const TaskConstMeta(
        debugName: "verify_migration_signature",
        argNames: [
          "serverPubkeyHex",
          "address",
          "fingerprint",
          "serverId",
          "signatureHex",
        ],
      );

  @override
  bool crateApiVerifySpkSignature({
    required String masterPubkeyHex,
    required String spkPubHex,
    required String signatureHex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(masterPubkeyHex, serializer);
          sse_encode_String(spkPubHex, serializer);
          sse_encode_String(signatureHex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVerifySpkSignatureConstMeta,
        argValues: [masterPubkeyHex, spkPubHex, signatureHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVerifySpkSignatureConstMeta => const TaskConstMeta(
    debugName: "verify_spk_signature",
    argNames: ["masterPubkeyHex", "spkPubHex", "signatureHex"],
  );

  @override
  String crateApiX3DhInitiate({
    required String ikSecretHex,
    required String ekSecretHex,
    required String peerIkHex,
    required String peerSpkHex,
    String? peerOpkHex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ikSecretHex, serializer);
          sse_encode_String(ekSecretHex, serializer);
          sse_encode_String(peerIkHex, serializer);
          sse_encode_String(peerSpkHex, serializer);
          sse_encode_opt_String(peerOpkHex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiX3DhInitiateConstMeta,
        argValues: [
          ikSecretHex,
          ekSecretHex,
          peerIkHex,
          peerSpkHex,
          peerOpkHex,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiX3DhInitiateConstMeta => const TaskConstMeta(
    debugName: "x3dh_initiate",
    argNames: [
      "ikSecretHex",
      "ekSecretHex",
      "peerIkHex",
      "peerSpkHex",
      "peerOpkHex",
    ],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DeviceBundle dco_decode_device_bundle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DeviceBundle(
      deviceId: dco_decode_String(arr[0]),
      deviceSecretHex: dco_decode_String(arr[1]),
      devicePubkeyHex: dco_decode_String(arr[2]),
    );
  }

  @protected
  E2eeSessionOutput dco_decode_e_2_ee_session_output(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return E2eeSessionOutput(
      newStateHex: dco_decode_String(arr[0]),
      payloadHex: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  IdentityBundle dco_decode_identity_bundle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return IdentityBundle(
      userId: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      masterSecretHex: dco_decode_String(arr[2]),
      masterPubkeyHex: dco_decode_String(arr[3]),
      avatarSeed: dco_decode_String(arr[4]),
    );
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  X25519Bundle dco_decode_x_25519_bundle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return X25519Bundle(
      secretHex: dco_decode_String(arr[0]),
      publicHex: dco_decode_String(arr[1]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DeviceBundle sse_decode_device_bundle(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceId = sse_decode_String(deserializer);
    var var_deviceSecretHex = sse_decode_String(deserializer);
    var var_devicePubkeyHex = sse_decode_String(deserializer);
    return DeviceBundle(
      deviceId: var_deviceId,
      deviceSecretHex: var_deviceSecretHex,
      devicePubkeyHex: var_devicePubkeyHex,
    );
  }

  @protected
  E2eeSessionOutput sse_decode_e_2_ee_session_output(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_newStateHex = sse_decode_String(deserializer);
    var var_payloadHex = sse_decode_String(deserializer);
    return E2eeSessionOutput(
      newStateHex: var_newStateHex,
      payloadHex: var_payloadHex,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  IdentityBundle sse_decode_identity_bundle(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userId = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_masterSecretHex = sse_decode_String(deserializer);
    var var_masterPubkeyHex = sse_decode_String(deserializer);
    var var_avatarSeed = sse_decode_String(deserializer);
    return IdentityBundle(
      userId: var_userId,
      displayName: var_displayName,
      masterSecretHex: var_masterSecretHex,
      masterPubkeyHex: var_masterPubkeyHex,
      avatarSeed: var_avatarSeed,
    );
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  X25519Bundle sse_decode_x_25519_bundle(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_secretHex = sse_decode_String(deserializer);
    var var_publicHex = sse_decode_String(deserializer);
    return X25519Bundle(secretHex: var_secretHex, publicHex: var_publicHex);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_device_bundle(DeviceBundle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.deviceSecretHex, serializer);
    sse_encode_String(self.devicePubkeyHex, serializer);
  }

  @protected
  void sse_encode_e_2_ee_session_output(
    E2eeSessionOutput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.newStateHex, serializer);
    sse_encode_String(self.payloadHex, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_identity_bundle(
    IdentityBundle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_String(self.masterSecretHex, serializer);
    sse_encode_String(self.masterPubkeyHex, serializer);
    sse_encode_String(self.avatarSeed, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_x_25519_bundle(X25519Bundle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.secretHex, serializer);
    sse_encode_String(self.publicHex, serializer);
  }
}
