[package]
name = "lonisle-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "lonisle_core"
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
prost.workspace = true
bytes.workspace = true
ed25519-dalek.workspace = true
rand.workspace = true
sha2.workspace = true
hmac.workspace = true
hex.workspace = true
base32.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
bip39.workspace = true
x25519-dalek.workspace = true
aes-gcm.workspace = true
hkdf.workspace = true
anyhow.workspace = true
base64.workspace = true
rcgen.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true

[build-dependencies]
prost-build.workspace = true
# 构建时自动下载 protoc 二进制，跨平台/交叉编译无需系统安装 protoc
protoc-bin-vendored = "3.2"

[dev-dependencies]
